[phases.setup]
nixPkgs = ['nodejs_22', 'chromium']

[phases.install]
cmds = ['npm ci']

[start]
cmd = "which chromium || find / -name 'chromium' -type f 2>/dev/null | head -5 && npm run scan -- https://fox.co.il"
